export const HERO_SLIDES = [
  {
    id: '1',
    title: '故宫博物院',
    subtitle: '明·清 | 北京',
    tag: '5A景区',
    tagColor: '#C8914A',
    description: '六百年紫禁城，见证王朝更迭，守望华夏文明',
    image: 'https://images.pexels.com/photos/2846814/pexels-photo-2846814.jpeg?auto=compress&cs=tinysrgb&w=1200',
    dynasty: '明清',
    type: '宫殿建筑',
  },
  {
    id: '2',
    title: '龙门石窟',
    subtitle: '北魏·唐 | 河南洛阳',
    tag: '世界遗产',
    tagColor: '#B5352A',
    description: '千佛凿壁，法相庄严，北魏至盛唐的石刻艺术巅峰',
    image: 'https://images.pexels.com/photos/3586966/pexels-photo-3586966.jpeg?auto=compress&cs=tinysrgb&w=1200',
    dynasty: '北魏·唐',
    type: '石窟寺',
  },
  {
    id: '3',
    title: '西安碑林博物馆',
    subtitle: '宋 | 陕西西安',
    tag: '国家一级',
    tagColor: '#2C4A3E',
    description: '碑石如林，书法圣殿，汇集历代名家墨迹精华',
    image: 'https://images.pexels.com/photos/1674049/pexels-photo-1674049.jpeg?auto=compress&cs=tinysrgb&w=1200',
    dynasty: '历代',
    type: '博物馆',
  },
  {
    id: '4',
    title: '布达拉宫',
    subtitle: '吐蕃·清 | 西藏拉萨',
    tag: '5A景区',
    tagColor: '#C8914A',
    description: '世界屋脊上的神圣宫殿，藏传佛教文化的精神圣地',
    image: 'https://images.pexels.com/photos/3280117/pexels-photo-3280117.jpeg?auto=compress&cs=tinysrgb&w=1200',
    dynasty: '吐蕃·清',
    type: '宗教建筑',
  },
];

export const CATEGORIES = [
  { id: 'all', label: '全部', icon: 'layers' },
  { id: 'heritage', label: '国保单位', icon: 'landmark' },
  { id: 'museum', label: '博物馆', icon: 'building' },
  { id: 'scenic', label: '5A景区', icon: 'mountain' },
  { id: 'ancient', label: '古建筑', icon: 'home' },
  { id: 'grotto', label: '石窟', icon: 'circle' },
  { id: 'tomb', label: '陵墓', icon: 'triangle' },
];

export const DYNASTY_FILTERS = [
  { id: 'all', label: '全朝代' },
  { id: 'shang', label: '商' },
  { id: 'zhou', label: '周' },
  { id: 'qin', label: '秦' },
  { id: 'han', label: '汉' },
  { id: 'wei', label: '魏晋' },
  { id: 'tang', label: '唐' },
  { id: 'song', label: '宋' },
  { id: 'yuan', label: '元' },
  { id: 'ming', label: '明' },
  { id: 'qing', label: '清' },
];

export const FEATURED_SITES = [
  {
    id: 'fs1',
    name: '秦始皇帝陵博物院',
    province: '陕西',
    city: '西安',
    category: 'museum',
    level: '5A',
    dynasty: '秦',
    type: '陵墓遗址',
    image: 'https://images.pexels.com/photos/2846814/pexels-photo-2846814.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['秦', '陵墓', '世界遗产'],
    rating: 4.9,
    distance: '12.3km',
    isStamped: true,
  },
  {
    id: 'fs2',
    name: '苏州博物馆',
    province: '江苏',
    city: '苏州',
    category: 'museum',
    level: '一级',
    dynasty: '现代',
    type: '综合博物馆',
    image: 'https://images.pexels.com/photos/1916817/pexels-photo-1916817.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['贝聿铭', '建筑', '综合'],
    rating: 4.8,
    distance: '2.1km',
    isStamped: false,
  },
  {
    id: 'fs3',
    name: '拙政园',
    province: '江苏',
    city: '苏州',
    category: 'scenic',
    level: '5A',
    dynasty: '明',
    type: '古典园林',
    image: 'https://images.pexels.com/photos/5737527/pexels-photo-5737527.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['明', '园林', '世界遗产'],
    rating: 4.7,
    distance: '3.5km',
    isStamped: false,
  },
  {
    id: 'fs4',
    name: '莫高窟',
    province: '甘肃',
    city: '敦煌',
    category: 'heritage',
    level: '国保',
    dynasty: '北魏·唐',
    type: '石窟寺',
    image: 'https://images.pexels.com/photos/3586966/pexels-photo-3586966.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['唐', '石窟', '世界遗产'],
    rating: 5.0,
    distance: '856km',
    isStamped: true,
  },
];

export const NEARBY_SITES = [
  {
    id: 'ns1',
    name: '雍和宫',
    type: '寺庙',
    dynasty: '清',
    distance: '0.8km',
    isOpen: true,
    image: 'https://images.pexels.com/photos/3493777/pexels-photo-3493777.jpeg?auto=compress&cs=tinysrgb&w=400',
    isFree: false,
    category: 'heritage',
  },
  {
    id: 'ns2',
    name: '国家博物馆',
    type: '博物馆',
    dynasty: '历代',
    distance: '1.4km',
    isOpen: true,
    image: 'https://images.pexels.com/photos/1674049/pexels-photo-1674049.jpeg?auto=compress&cs=tinysrgb&w=400',
    isFree: true,
    category: 'museum',
  },
  {
    id: 'ns3',
    name: '天坛公园',
    type: '古建筑',
    dynasty: '明·清',
    distance: '2.6km',
    isOpen: true,
    image: 'https://images.pexels.com/photos/2846814/pexels-photo-2846814.jpeg?auto=compress&cs=tinysrgb&w=400',
    isFree: false,
    category: 'scenic',
  },
];

export const JOURNEY_TEMPLATES = [
  {
    id: 'jt1',
    title: '西安三日文化深度游',
    days: 3,
    siteCount: 8,
    theme: '秦唐盛世',
    image: 'https://images.pexels.com/photos/2846814/pexels-photo-2846814.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['秦', '唐', '历史'],
    sites: ['秦始皇帝陵', '大雁塔', '陕西历史博物馆', '城墙', '碑林'],
  },
  {
    id: 'jt2',
    title: '苏杭江南水乡两日',
    days: 2,
    siteCount: 6,
    theme: '宋明园林',
    image: 'https://images.pexels.com/photos/5737527/pexels-photo-5737527.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['明', '园林', '水乡'],
    sites: ['拙政园', '苏州博物馆', '西湖', '灵隐寺'],
  },
];

export const STAMPS_DATA = [
  {
    id: 'st1',
    name: '故宫',
    image: 'https://images.pexels.com/photos/2846814/pexels-photo-2846814.jpeg?auto=compress&cs=tinysrgb&w=200',
    date: '2024.03.15',
    unlocked: true,
    color: '#C8914A',
  },
  {
    id: 'st2',
    name: '莫高窟',
    image: 'https://images.pexels.com/photos/3586966/pexels-photo-3586966.jpeg?auto=compress&cs=tinysrgb&w=200',
    date: '2024.02.08',
    unlocked: true,
    color: '#2C4A3E',
  },
  {
    id: 'st3',
    name: '秦陵',
    image: 'https://images.pexels.com/photos/2846814/pexels-photo-2846814.jpeg?auto=compress&cs=tinysrgb&w=200',
    date: '2023.11.20',
    unlocked: true,
    color: '#B5352A',
  },
  {
    id: 'st4',
    name: '布达拉宫',
    image: 'https://images.pexels.com/photos/3280117/pexels-photo-3280117.jpeg?auto=compress&cs=tinysrgb&w=200',
    date: '未解锁',
    unlocked: false,
    color: '#9A8A78',
  },
  {
    id: 'st5',
    name: '龙门石窟',
    image: 'https://images.pexels.com/photos/3586966/pexels-photo-3586966.jpeg?auto=compress&cs=tinysrgb&w=200',
    date: '未解锁',
    unlocked: false,
    color: '#9A8A78',
  },
  {
    id: 'st6',
    name: '苏州园林',
    image: 'https://images.pexels.com/photos/5737527/pexels-photo-5737527.jpeg?auto=compress&cs=tinysrgb&w=200',
    date: '未解锁',
    unlocked: false,
    color: '#9A8A78',
  },
];

export const ACHIEVEMENTS = [
  {
    id: 'ac1',
    title: '唐代建筑鉴赏家',
    description: '打卡10处唐代建筑遗址',
    progress: 7,
    total: 10,
    icon: 'award',
    color: '#C8914A',
    unlocked: false,
  },
  {
    id: 'ac2',
    title: '石窟重度爱好者',
    description: '探访全国四大石窟',
    progress: 2,
    total: 4,
    icon: 'star',
    color: '#2C4A3E',
    unlocked: false,
  },
  {
    id: 'ac3',
    title: '文化旅行者',
    description: '完成首次文化打卡',
    progress: 1,
    total: 1,
    icon: 'check',
    color: '#4A8C6F',
    unlocked: true,
  },
  {
    id: 'ac4',
    title: '博物馆常客',
    description: '参观20家博物馆',
    progress: 12,
    total: 20,
    icon: 'building',
    color: '#B5352A',
    unlocked: false,
  },
];

export const PROVINCES_VISITED = ['北京', '陕西', '甘肃', '江苏', '浙江', '四川'];

export const USER_STATS = {
  sitesVisited: 47,
  provincesExplored: 12,
  dynastiesStudied: 8,
  stampsCollected: 23,
  journeysCompleted: 6,
  totalDistance: 8432,
};
